version: '3.9'
services:
  nginx-mailcow:
    labels:
      traefik.docker.network: proxy
      traefik.enable: "true"
      traefik.http.routers.nginx-mailcow-secure.entrypoints: websecure
      traefik.http.routers.nginx-mailcow-secure.middlewares: default@file
      traefik.http.routers.nginx-mailcow-secure.rule: Host(`pi.post44.de`,`autodiscover.post44.de`,`autoconfig.post44.de`,`mta-sts.post44.de`,`mail.post44.de`)
      traefik.http.routers.nginx-mailcow-secure.service: nginx-mailcow
      traefik.http.routers.nginx-mailcow-secure.tls: "true"
      traefik.http.routers.nginx-mailcow-secure.tls.certresolver: http_resolver
      traefik.http.routers.nginx-mailcow.entrypoints: web
      traefik.http.routers.nginx-mailcow.rule: Host(`pi.post44.de`,`autodiscover.post44.de`,`autoconfig.post44.de`,`mta-sts.post44.de`,`mail.post44.de`)
      traefik.http.services.nginx-mailcow.loadbalancer.server.port: "80"
    networks:
      proxy:
  certdumper:
    image: ghcr.io/kereis/traefik-certs-dumper:ci-manual-manifest
    restart: unless-stopped
    network_mode: none
    command: --restart-containers mailcowdockerized-postfix-mailcow-1,mailcowdockerized-dovecot-mailcow-1
    volumes:
      - /data/docker/traefik-crowdsec-stack/traefik:/traefik:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/assets/ssl:/output:rw
    environment:
      DOMAIN: ${MAILCOW_HOSTNAME}
      ACME_FILE_PATH: "/traefik/acme_letsencrypt.json"
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
networks:
  proxy:
    external: true
